version: '3'
services:
  portal-eureka:
    image: stainii/portal-eureka:1.0.0
    volumes:
      - /app/portal/eureka:/tmp
    ports:
      - 8761:8761
    expose:
      - "8761"

  portal-config:
    image: stainii/portal-config:1.0.0
    volumes:
      - /app/portal/config/app/:/tmp
    ports:
      - 2000:2000

  portal-core-db:
    image: postgres
    volumes:
      - /app/portal/core/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: portal-core
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-core

  portal-core-app:
    image: stainii/portal-front-end-core:1.0.1-SNAPSHOT
    volumes:
      - /app/portal/core/app/:/tmp
    ports:
      - 2001:2001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  portal-housagotchi-db:
    image: postgres
    volumes:
      - /app/portal/housagotchi/db/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi

  portal-housagotchi-app:
    image: stainii/portal-housagotchi:1.0.1-SNAPSHOT
    volumes:
      - /app/portal/housagotchi/app/:/tmp
    ports:
      - 2002:2002
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  portal-notifications-db:
      image: postgres
      volumes:
        - /app/portal/notifications/db/data:/var/lib/postgresql/data
      ports:
        - "5434:5432"
      environment:
        POSTGRES_USER: portal-notifications
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: portal-notifications

  portal-notifications-app:
    image: stainii/portal-notifications:1.0.0-SNAPSHOT
    volumes:
      - /app/portal/notifications/app/:/tmp
    ports:
      - 2003:2003
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  portal-notifications-email-plugin:
    image: stainii/portal-notifications-email-plugin:1.0.1-SNAPSHOT
    volumes:
      - /app/portal/notifications/email-plugin/:/tmp
    ports:
      - 2004:2004
    environment:
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SMTP_AUTH: ${EMAIL_SMTP_AUTH}
      EMAIL_STARTTLS: ${EMAIL_STARTTLS}

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - /app/portal/rabittmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

