version: '3'
services:
  portal-eureka:
    image: stainii/portal-eureka:1.0.2
    volumes:
      - portal-eureka:/tmp
      #- /app/portal/eureka:/tmp
    ports:
      - 8761:8761
    deploy:
      resources:
        limits:
          memory: 500M

  portal-front-end-db:
    image: "postgres:10.5"
    volumes:
      - portal-front-end-db:/var/lib/postgresql/data
      #- /app/portal/front-end/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: portal-front-end
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-front-end
    deploy:
      resources:
        limits:
          memory: 100M

  portal-front-end-app:
    image: stainii/portal-front-end:2.1.0
    volumes:
      - portal-front-end-app:/tmp
      #- /app/portal/front-end/app/:/tmp
    ports:
      - 2001:2001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_OPTS_FRONT_END: ${JAVA_OPTS_FRONT_END}
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-housagotchi-db:
    image: "postgres:10.5"
    volumes:
      - portal-housagotchi-db:/var/lib/postgresql/data
      #- /app/portal/housagotchi/db/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi
    deploy:
      resources:
        limits:
          memory: 100M

  portal-housagotchi-app:
    image: stainii/portal-recurring-tasks:1.0.0-SNAPSHOT
    volumes:
      - portal-housagotchi-app/:/tmp
      #- /app/portal/housagotchi/app/:/tmp
    ports:
      - 2002:2002
    environment:
      DEPLOYMENT_NAME: Housagotchi
      POSTGRES_URL: ${POSTGRES_URL_HOUSAGOTCHI}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME_HOUSAGOTCHI}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_HOUSAGOTCHI}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      JAVA_OPTS_HOUSAGOTCHI: ${JAVA_OPTS_HOUSAGOTCHI}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:p
          memory: 400M

  portal-notifications-db:
    image: "postgres:10.5"
    volumes:
      - portal-notifications-db:/var/lib/postgresql/data
      #- /app/portal/notifications/db/data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: portal-notifications
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-notifications
    deploy:
      resources:
        limits:
          memory: 100M

  portal-notifications-app:
    image: stainii/portal-notifications:2.0.0
    volumes:
      - portal-notifications-app:/tmp
      #- /app/portal/notifications/app/:/tmp
    ports:
      - 2003:2003
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_OPTS_NOTIFICATIONS: ${JAVA_OPTS_NOTIFICATIONS}
      BASE_URL: ${BASE_URL}notification/
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-notifications-email-plugin:
    image: stainii/portal-notifications-email-plugin:1.0.2
    volumes:
      - portal-notifications-email-plugin:/tmp
      #- /app/portal/notifications/email-plugin/:/tmp
    ports:
      - 2004:2004
    environment:
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SMTP_AUTH: ${EMAIL_SMTP_AUTH}
      EMAIL_STARTTLS: ${EMAIL_STARTTLS}
      JAVA_OPTS_NOTIFICATIONS_EMAIL_PLUGIN: ${JAVA_OPTS_NOTIFICATIONS_EMAIL_PLUGIN}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 300M

#portal-portfolio-db:
#  image: mongo:4.0.6
#  environment:
#    MONGO_INITDB_ROOT_USERNAME: ${DATABASE_USERNAME_PORTFOLIO}
#    MONGO_INITDB_ROOT_PASSWORD: ${DATABASE_PASSWORD_PORTFOLIO}
#    MONGO_INITDB_DATABASE: ${DATABASE_NAME_PORTFOLIO}
#    MONGODB_USER: ${DATABASE_USERNAME_PORTFOLIO}
#    MONGODB_PASS: ${DATABASE_PASSWORD_PORTFOLIO}
#  volumes:
#    - /home/stijn/portal/portfolio/db/data/:/data/db
#    - /home/stijn/portal/portfolio/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
#  ports:
#    - 27017:27017

#  portal-portfolio-app:
#    image: stainii/portal-portfolio:1.0.1
#    ports:
#      - 8080:8080
#    environment:
#      DATABASE_HOST_PORTFOLIO: ${DATABASE_HOST_PORTFOLIO}
#      DATABASE_PORT_PORTFOLIO: ${DATABASE_PORT_PORTFOLIO}
#      DATABASE_NAME_PORTFOLIO: ${DATABASE_NAME_PORTFOLIO}
#      DATABASE_USERNAME_PORTFOLIO: ${DATABASE_USERNAME_PORTFOLIO}
#      DATABASE_PASSWORD_PORTFOLIO: ${DATABASE_PASSWORD_PORTFOLIO}
#      JAVA_OPTS_PORTFOLIO: ${JAVA_OPTS_PORTFOLIO}
#      JWT_SECRET: ${JWT_SECRET}
#      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
#    deploy:
#      resources:
#        limits:
#          memory: 400M

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - portal-rabbitmq:/etc/rabbitmq/rabbitmq.config
      #- /app/portal/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    deploy:
      resources:
        limits:
          memory: 512M

  portal-authentication-db:
    image: "postgres:11.0"
    volumes:
      - portal-authentication-db:/var/lib/postgresql/data
      #- /app/portal/authentication/db/data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: portal-authentication
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-authentication
    deploy:
      resources:
        limits:
          memory: 100M

  portal-authentication-app:
    image: stainii/portal-authentication:1.0.1
    volumes:
      - portal-authentication-app:/tmp
      #- /app/portal/authentication/app/:/tmp
    ports:
      - 9100:9100
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-proxy:
    image: stainii/portal-proxy:2.0.0
    volumes:
      - portal-proxy:/tmp
    ports:
      - 2000:2000
    environment:
      JAVA_OPTS_PROXY: ${JAVA_OPTS_PROXY}
      JWT_SECRET: ${JWT_SECRET}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 300M

#  portal-image-editor:
#    image: stainii/portal-image-editor:1.0.0-SNAPSHOT
#    ports:
#      - 3000:3000
#    environment:
#      HOSTNAME: portal-image-editor
#      EUREKA_HOST: portal-eureka
#    deploy:
#      resources:
#        limits:
#          memory: 100M


  portal-todo-db:
    image: "mongo:4.2.1"
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME_TODO}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME_TODO}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD_TODO}
    volumes:
      - /c/Users/SHFAR21/OneDrive/Documenten/projecten/portal/portal-todo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - portal-todo-db:/data/db
      #- /home/stijn/portal/todo/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      #- /home/stijn/portal/todo/db/data/:/data/db
    deploy:
      resources:
        limits:
          memory: 50M

  portal-todo-app:
    image: stainii/portal-todo:1.0.0-SNAPSHOT
    volumes:
      - portal-todo-app:/tmp
      #- /app/portal/todo/app/:/tmp
    ports:
      - 2007:2007
    environment:
      JAVA_OPTS_TODO: ${JAVA_OPTS_TODO}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST_TODO: ${DATABASE_HOST_TODO}
      DATABASE_PORT_TODO: ${DATABASE_PORT_TODO}
      DATABASE_USERNAME_TODO: ${DATABASE_USERNAME_TODO}
      DATABASE_PASSWORD_TODO: ${DATABASE_PASSWORD_TODO}
      DATABASE_NAME_TODO: ${DATABASE_NAME_TODO}
      EUREKA_SERVICE_URL: ${EUREKA_SERVICE_URL}
    deploy:
      resources:
        limits:
          memory: 400M

volumes:
  portal-front-end-db:
    external: true
  portal-front-end-app:
      external: true
  portal-housagotchi-db:
    external: true
  portal-housagotchi-app:
    external: true
  portal-notifications-db:
    external: true
  portal-notifications-app:
    external: true
  portal-notifications-email-plugin:
    external: true
  portal-authentication-db:
    external: true
  portal-authentication-app:
    external: true
  portal-todo-db:
    external: true
  portal-todo-app:
    external: true
  portal-proxy:
      external: true
  portal-rabbitmq:
    external: true
  portal-eureka:
    external: true