version: '3'
services:

  portal-front-end-db:
    image: "postgres:10.5"
    volumes:
    - /app/portal/front-end/db/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: portal-front-end
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-front-end
    deploy:
      resources:
        limits:
          memory: 50M

  portal-housagotchi-db:
    image: "postgres:10.5"
    volumes:
    - /app/portal/housagotchi/db/data:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi
    deploy:
      resources:
        limits:
          memory: 50M

  portal-notifications-db:
    image: "postgres:10.5"
    volumes:
    - /app/portal/notifications/db/data:/var/lib/postgresql/data
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: portal-notifications
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-notifications
    deploy:
      resources:
        limits:
          memory: 50M

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
    - /app/portal/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    deploy:
      resources:
        limits:
          memory: 512M

  portal-authentication-db:
    image: "postgres:11.0"
    volumes:
    - /app/portal/authentication/db/data:/var/lib/postgresql/data
    ports:
    - "5435:5432"
    environment:
      POSTGRES_USER: portal-authentication
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-authentication
    deploy:
      resources:
        limits:
          memory: 50M