version: '3'
services:

  portal-front-end-db:
    image: "postgres:10.5"
    volumes:
      - portal-front-end-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_FRONT_END}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FRONT_END}
      POSTGRES_DB: portal-front-end
    deploy:
      resources:
        limits:
          memory: 50M

  portal-housagotchi-db:
    image: "postgres:10.5"
    volumes:
      - portal-housagotchi-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi
    deploy:
      resources:
        limits:
          memory: 50M

  portal-notifications-db:
    image: "postgres:10.5"
    volumes:
      - portal-notifications-db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: portal-notifications
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-notifications
    deploy:
      resources:
        limits:
          memory: 50M

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - portal-rabbitmq:/etc/rabbitmq/rabbitmq.config
    deploy:
      resources:
        limits:
          memory: 512M

  portal-authentication-db:
    image: "postgres:11.0"
    volumes:
      - portal-authentication-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: portal-authentication
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-authentication
    deploy:
      resources:
        limits:
          memory: 50M

  portal-health-db:
    image: "postgres:12.1"
    volumes:
      - portal-health-db:/var/lib/postgresql/data
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: portal-health
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-health
    deploy:
      resources:
        limits:
          memory: 50M

  portal-setlist-db:
    image: "postgres:12.2"
    volumes:
      - portal-setlist-db:/var/lib/postgresql/data
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: portal-setlist
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-setlist
    deploy:
      resources:
        limits:
          memory: 50M

  portal-todo-db:
    image: "mongo:4.2.1"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME_TODO}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME_TODO}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD_TODO}
    volumes:
      - /c/Users/SHFAR21/projecten/portal/portal-todo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - portal-todo-db:/data/db
    deploy:
      resources:
        limits:
          memory: 50M

  portal-social-db:
    image: "postgres:12.2"
    volumes:
      - portal-social-db:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: portal-social
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-social
    deploy:
      resources:
        limits:
          memory: 50M

  portal-social-recurring-tasks-db:
    image: "postgres:12.2"
    volumes:
      - portal-social-recurring-tasks-db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: portal-social-recurring-tasks
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-social-recurring-tasks
    deploy:
      resources:
        limits:
          memory: 50M

  portal-image:
    image: "stainii/portal-image:1.0.0-SNAPSHOT"
    volumes:
      - portal-image:/app/data
    ports:
      - "3000:3000"
    environment:
      EUREKA_HOST: portal-eureka
    deploy:
      resources:
        limits:
          memory: 150M
  portal-eureka:
    image: stainii/portal-eureka:1.0.2
    volumes:
      - portal-eureka:/tmp
    ports:
      - 8761:8761
    deploy:
      resources:
        limits:
          memory: 500M

volumes:
  portal-front-end-db:
    external: true
  portal-housagotchi-db:
    external: true
  portal-notifications-db:
    external: true
  portal-authentication-db:
    external: true
  portal-todo-db:
    external: true
  portal-rabbitmq:
    external: true
  portal-health-db:
    external: true
  portal-setlist-db:
    external: true
  portal-social-db:
    external: true
  portal-social-recurring-tasks-db:
    external: true
  portal-image:
    external: true
  portal-eureka:
    external: true