version: '3'
services:

  portal-front-end-db:
    image: "postgres:10.5"
    volumes:
    - portal-front-end-db:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: portal-front-end
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-front-end
    deploy:
      resources:
        limits:
          memory: 50M

  portal-housagotchi-db:
    image: "postgres:10.5"
    volumes:
    - portal-housagotchi-db:/var/lib/postgresql/data
    ports:
    - "5433:5432"
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi
    deploy:
      resources:
        limits:
          memory: 50M

  portal-notifications-db:
    image: "postgres:10.5"
    volumes:
    - portal-notifications-db:/var/lib/postgresql/data
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: portal-notifications
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-notifications
    deploy:
      resources:
        limits:
          memory: 50M

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
    - portal-rabbitmq:/etc/rabbitmq/rabbitmq.config
    deploy:
      resources:
        limits:
          memory: 512M

  portal-authentication-db:
    image: "postgres:11.0"
    volumes:
    - portal-authentication-db:/var/lib/postgresql/data
    ports:
    - "5435:5432"
    environment:
      POSTGRES_USER: portal-authentication
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-authentication
    deploy:
      resources:
        limits:
          memory: 50M

  portal-todo-db:
    image: "mongo:4.2.1"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME_TODO}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME_TODO}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD_TODO}
    volumes:
      - /c/Users/SHFAR21/OneDrive/Documenten/projecten/portal/portal-todo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - portal-todo-db:/data
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  portal-front-end-db:
    external: true
  portal-housagotchi-db:
      external: true
  portal-notifications-db:
      external: true
  portal-authentication-db:
      external: true
  portal-todo-db:
    external: true
  portal-rabbitmq:
    external: true