version: '3'
services:
  portal-eureka:
    image: stainii/portal-eureka:1.0.1
    volumes:
    - /app/portal/eureka:/tmp
    ports:
    - 8761:8761
    deploy:
      resources:
        limits:
          memory: 500M

  portal-front-end-db:
    image: "postgres:10.5"
    volumes:
    - /app/portal/front-end/db/data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: portal-front-end
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-front-end
    deploy:
      resources:
        limits:
          memory: 100M

  portal-front-end-app:
    image: stainii/portal-front-end:2.0.1
    volumes:
    - /app/portal/front-end/app/:/tmp
    ports:
    - 2001:2001
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_OPTS_PORTAL_FRONT_END: ${JAVA_OPTS_PORTAL_FRONT_END}
      JWT_SECRET: ${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-housagotchi-db:
    image: "postgres:10.5"
    volumes:
    - /app/portal/housagotchi/db/data:/var/lib/postgresql/data
    ports:
    - 5433:5432
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi
    deploy:
      resources:
        limits:
          memory: 100M

  portal-housagotchi-app:
    image: stainii/portal-housagotchi:2.0.2
    volumes:
    - /app/portal/housagotchi/app/:/tmp
    ports:
    - 2002:2002
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_OPTS_PORTAL_HOUSAGOTCHI: ${JAVA_OPTS_PORTAL_HOUSAGOTCHI}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-notifications-db:
    image: "postgres:10.5"
    volumes:
    - /app/portal/notifications/db/data:/var/lib/postgresql/data
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: portal-notifications
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-notifications
    deploy:
      resources:
        limits:
          memory: 100M

  portal-notifications-app:
    image: stainii/portal-notifications:1.0.1
    volumes:
    - /app/portal/notifications/app/:/tmp
    ports:
    - 2003:2003
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JAVA_OPTS_PORTAL_NOTIFICATIONS: ${JAVA_OPTS_PORTAL_NOTIFICATIONS}
      BASE_URL: ${BASE_URL}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-notifications-email-plugin:
    image: stainii/portal-notifications-email-plugin:1.0.1
    volumes:
    - /app/portal/notifications/email-plugin/:/tmp
    ports:
    - 2004:2004
    environment:
      EMAIL_RECIPIENT: ${EMAIL_RECIPIENT}
      EMAIL_SENDER: ${EMAIL_SENDER}
      EMAIL_SUBJECT: ${EMAIL_SUBJECT}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      EMAIL_SMTP_AUTH: ${EMAIL_SMTP_AUTH}
      EMAIL_STARTTLS: ${EMAIL_STARTTLS}
      JAVA_OPTS_PORTAL_NOTIFICATIONS_EMAIL_PLUGIN: ${JAVA_OPTS_PORTAL_NOTIFICATIONS_EMAIL_PLUGIN}
    deploy:
      resources:
        limits:
          memory: 300M

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
    - /app/portal/rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    deploy:
      resources:
        limits:
          memory: 512M

  portal-authentication-db:
    image: "postgres:11.0"
    volumes:
    - /app/portal/authentication/db/data:/var/lib/postgresql/data
    ports:
    - "5435:5432"
    environment:
      POSTGRES_USER: portal-authentication
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-authentication
    deploy:
      resources:
        limits:
          memory: 100M

  portal-authentication-app:
    image: stainii/portal-authentication:1.0.1
    volumes:
    - /app/portal/authentication/app/:/tmp
    ports:
    - 9100:9100
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 400M

  portal-proxy:
    image: stainii/portal-proxy:1.0.0
    volumes:
    - /app/portal/proxy/:/tmp
    ports:
    - 2000:2000
    environment:
      JAVA_OPTS_PORTAL_PROXY: ${JAVA_OPTS_PORTAL_PROXY}
      JWT_SECRET: ${JWT_SECRET}
    deploy:
      resources:
        limits:
          memory: 300M

  portal-image-editor:
    image: stainii/portal-image-editor:1.0.0-SNAPSHOT
    ports:
      - 3000:3000
    environment:
      HOSTNAME: portal-image-editor
      EUREKA_HOST: portal-eureka
    deploy:
      resources:
        limits:
          memory: 100M