version: '3.8'
services:

  portal-front-end-db:
    image: "postgres:10.5"
    volumes:
      - portal-front-end-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME_FRONT_END}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_FRONT_END}
      POSTGRES_DB: portal-front-end
    deploy:
      resources:
        limits:
          memory: 50M

  portal-rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - portal-rabbitmq:/etc/rabbitmq/rabbitmq.config
    deploy:
      resources:
        limits:
          memory: 512M

  portal-authentication-db:
    image: "postgres:11.0"
    volumes:
      - portal-authentication-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: portal-authentication
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-authentication
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  portal-front-end-db:
    external: true
  portal-authentication-db:
    external: true
  portal-rabbitmq:
    external: true