version: '3'
services:

  portal-housagotchi-db:
    image: "postgres:10.5"
    volumes:
      - portal-housagotchi-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: portal-housagotchi
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: portal-housagotchi
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  portal-housagotchi-db:
    external: true