version: '3'
services:

  portal-image:
    image: "stainii/portal-image:1.0.0-SNAPSHOT"
    volumes:
      - portal-image:/app/data
    ports:
      - "3000:3000"
    environment:
      EUREKA_HOST: portal-eureka
      HOST_NAME: portal-image
    deploy:
      resources:
        limits:
          memory: 150M

volumes:
  portal-image:
    external: true