version: '3'
services:

  portal-todo-db:
    image: "mongo:4.2.1"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME_TODO}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME_TODO}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD_TODO}
    volumes:
      - /Users/stijnhooft/projecten/portal/portal-todo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - portal-todo-db:/data/db
    deploy:
      resources:
        limits:
          memory: 50M


volumes:
  portal-todo-db:
    external: true
