version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-stijnhooft@hotmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - /Users/stijnhooft/app/portal/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"

  mongo-express-todo:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOST_TODO}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME_TODO}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD_TODO}

  mongo-express-activity:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${DATABASE_HOST_ACTIVITY}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DATABASE_USERNAME_ACTIVITY}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DATABASE_PASSWORD_ACTIVITY}