version: '3'
services:

  portal-weather:
    image: "stainii/portal-weather:1.0.0-SNAPSHOT"
    ports:
      - "2008:2008"
    environment:
      - JAVA_OPTS_WEATHER=${JAVA_OPTS_WEATHER}
      - CACHE_PATH=${WEATHER_CACHE_PATH}
      - CACHE_FORECASTS_HOURS_CONSIDERED_UP_TO_DATE=${WEATHER_CACHE_FORECASTS_HOURS_CONSIDERED_UP_TO_DATE}
      - CACHE_FORECASTS_MAX_MB=${WEATHER_CACHE_FORECASTS_MAX_MB}
      - CACHE_FORECASTS_MAX_NO_OF_ENTRIES=${WEATHER_CACHE_FORECASTS_MAX_NO_OF_ENTRIES}
      - CACHE_LOCATIONS_MAX_MB=${WEATHER_CACHE_LOCATIONS_MAX_MB}
      - CACHE_LOCATIONS_MAX_NO_OF_ENTRIES=${WEATHER_CACHE_LOCATIONS_MAX_NO_OF_ENTRIES}
      - OPENWEATHERMAP_ENABLED=${WEATHER_OPENWEATHERMAP_ENABLED}
      - OPENWEATHERMAP_ORDER=${WEATHER_OPENWEATHERMAP_ORDER}
      - OPENWEATHERMAP_API_KEY=${WEATHER_OPENWEATHERMAP_API_KEY}
      - EUREKA_SERVICE_URL=${EUREKA_SERVICE_URL}
    volumes:
      - portal-weather:/tmp
    deploy:
      resources:
        limits:
          memory: 250M


volumes:
  portal-weather:
    external: true
